# Generated by Django 5.2.1 on 2025-05-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='data_od_birth',
            new_name='data_of_birth',
        ),
    ]
