# Generated by Django 5.2.1 on 2025-05-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_data_od_birth_customer_data_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
